site_name: Richèl's Teaching

repo_url: https://github.com/richelbilderbeek/teaching

nav:
  - Home: index.md
  - Teaching:
    - Activities: activities.md
    - Teaching material: teaching_material.md
    - Lesson plans: lesson_plans.md
    - Reflections: reflections.md
    - Evaluations: evaluations.md
  - Exercise procedure:
    - Duo's in breakout rooms: exercise_procedures/duos_in_breakout_rooms.md
    - Work in silence: exercise_procedures/work_in_silent.md
  - Workflows:
    - git: workflows/git_workflow.md
    - GitHub: workflows/github_workflow.md
  - Misc:
    - Who is Richèl: who_is_richel/README.md

theme:
  name: material
  greetings: Welcome to Richèl's Teaching
  font:
    text: Lato
    code: JetBrains Mono

  logo: assets/r_written.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - navigation.expand
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
    
extra_css:
  - stylesheets/extra.css
      
markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


