# Check that there is correct spelling in all files
name: Check spelling

# Check spelling on the 21st day of the month.
# 21st as the first letter of this repo is the 21st letter in the alphabet.
on:
  push:
    paths:
      - .github/workflows/check_spelling.yaml
      - 'docs/**'
      - .wordlist.txt
  pull_request:
    paths:
      - .github/workflows/check_spelling.yaml
      - 'docs/**'
      - .wordlist.txt
  schedule:
  - cron: "0 0 21 * *"


jobs:
  check_spelling:

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - uses: igsekor/pyspelling-any@v1.0.4



