name: Create website

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/create_website.yaml
      - 'docs/**'
      - mkdocs.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt natsort

      - name: Render HTML
        run: mkdocs gh-deploy --force
